import "../globals.css";
import { Toaster } from "react-hot-toast";
import Header from "@/components/Layout/header/header";
import Footer from "@/components/Layout/footer/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black antialiased h-full bg-hero-pattern bg-cover bg-no-repeat bg-center">
        <Header />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
